### ISSUE TITLE
June Patch

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/12v12#150]
- [x] Party highlighting
- [x] Fix Smart Random #135 
- [x] Add 6 new Perks
- [x] Add some voting options at start of game.  #100 
- [x] Import Team Swtich button/mechanic from Redux #7 
- [x] Fix an exploit related to neutral items #122 
- [x] Update Logo and Load Screen
- [x] Fix sprout being difficult to level up and failing on enemy cast #97 #98 
- [x] Show neutral items on scoreboard #123 

Some of these should be applied to Overthrow 2.0

**Comment by adminnz** [comment]
I cannot see any code relating to the 6 new perks is not on github. 
Has this project now become closed source?

**Comment by Sheodar** [comment]
https://github.com/dota2unofficial/12v12/tree/june_patch

**Comment by adminnz** [comment]
Thanks @Sheodar, was not expecting the latest released code to not be in the master branch.

**Comment by Sheodar** [comment]
@adminnz it has some problems for. When we check it, we'll merge it (i think)

**Comment by darklordabc** [comment]
Done
